config/routes.rb
Rails.application.routes.draw do
  resources :items
  get 'profiles/new'
  resources :profiles

# Add devise registrations controller to allow after sign up path
  devise_for :users, controllers: { registrations: "registrations" }
  root "home#index"
  get 'home/index'

  #  Add about page route
  get "about", to: "home#about"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :seller
      can :manage, Item
    elsif user.has_role? :buyer
      can :read, :all
    end
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, ProfilePictureUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, ProfilePictureUploader
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile

  after_create :assign_role

  def assign_role

    if user_type == 'buyer'
      add_role :buyer
    elsif user_type == 'seller'
      add_role :seller
    elsif user_type == 'admin'
      add_role :admin
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #before_action-> before executing any controller perform this action
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
# Allowing the parameter to be accepted by the decise (similar to params require under every controller)
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_type])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user = current_user
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :picture, :description, :price, :posted_date, :expiry_date, :user_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      flash[:notice] = "You have successfully created a new Profile!"
      redirect_to profile_path(@profile)
    else
      render :new
    end
  end

def index
  @profile = Profile.all
end

def show
  @profile = current_user.profile
end

  private

  def profile_params
    params.require(:profile).permit(:first_name, :last_name, :biography, :picture)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    new_profile_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/about.html.erb
<h1>About iSell</h1>

<p>iSell is a CFA based startup selling questionable goods.</p>
<p>Call us on 1300-CALL for more info</p>

app/views/home/index.html.erb
<div class="jumbatron">
<h1>iSell</h1>
<h3>Where people come to buy stuff</h3>
<!-- Add links that look like buttons via bootstrap  -->
<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
<%= link_to "Sign In", new_user_session_path, class: "btn btn-info" %>

</div>


<!-- Add an About/Contact me page that can be linked through navbar -->
<!-- Add background image? on homepage -->
<!-- Add more prominent sign up and sign in buttons on the homepage -->

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :picture, as: :file %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :posted_date %>
    <%= f.input :expiry_date %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Picture</th>
      <th>Description</th>
      <th>Price</th>
      <th>Posted date</th>
      <th>Expiry date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= image_tag(item.picture_url(:thumbnail), :width => 50, :height => 50) %></td>
        <td><%= item.description %></td>
        <td><%= item.price %></td>
        <td><%= item.posted_date %></td>
        <td><%= item.expiry_date %></td>
        <td><%= item.user %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.has_role? :seller %>
<%= link_to 'New Item', new_item_path %>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @item.picture %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Posted date:</strong>
  <%= @item.posted_date %>
</p>

<p>
  <strong>Expiry date:</strong>
  <%= @item.expiry_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @item.user %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ISell</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Render partial navbar across site -->
    <%= render "shared/navbar" %>
    <div class="container">

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= simple_form_for(profile) do |f| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :biography %>
    <%= f.text_field :biography %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/new.html.erb
<h1>New Profiles</h1>

<%= render 'form', profile: @profile %>

app/views/profiles/show.html.erb
  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">

  <p>
    <strong>First name:</strong>
    <%= @profile.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= @profile.last_name %>
  </p>

  <p>
    <strong>Photo:</strong>
    <%= image_tag(@profile.picture_url(:thumbnail), :width => 50, :height => 50) %>
  </p>

  <% if current_user.profile = @profile %>
    <%= link_to 'Edit', edit_profile_path(@profile), class: 'btn btn-warning' %>
  <% end %>

  </div></div></div></div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">iSell</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "About", about_path %></li>
        <li class="dropdown">
        </li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="caret"></span></a>
          <ul class="dropdown-menu">

            <% if user_signed_in? %>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_registration_path %> </li>
              <li><%= link_to "Sign In", new_user_session_path %> </li>
            <% end %>

          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>